

services:
  web:
    image: nginx
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - carro-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - carro-network

  db:
    image: mysql:8.4.0
    container_name: db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "$DB_DATABASE"
      MYSQL_USER: "$DB_USER"
      MYSQL_PASSWORD: "$DB_PASSWORD"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes  
      
  composer:
    image: composer:2.7.2
    user: "1000:1000"
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
    networks:
      - carro-network

networks:
  carro-network:
    driver: bridge
