<div class="row">
        <form action="<?= route("authenticate")?>" method="POST" class="col s12">
            <div class="col s12 m12 l12">
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">mail</i>
                        <input id="mailUser" name="user[email]" type="email" class="validate" >
                        <label for="mailUser">e-mail</label>
                    </div>
                </div>
                <div class="col s12 l12 m12 ">
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix">password</i>
                            <input id="passWord1User" name="user[password]" type="password" class="validate" >
                            <label for="passWord1User">Senha</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col s12 m12 l12 center">
                <button class="waves-effect waves-light btn-small blue darken-4" type="submit">Login</button>
            </div>
        </form>
    </div>