name: Continuous Integration with Github Actions

on:
  push:


jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.head_commit.id }}
    
      - name: Composer install
        run: composer install

      - name: PHPUNIT
        run: ./vendor/bin/phpunit
