
<?php
define("DB_PATH", "../../../database/brand.txt");

$brands = file(DB_PATH,FILE_IGNORE_NEW_LINES);
?>

<section>
<div class="row">
      <div class="col">
        <h4>Marcas Informadas</h4>

      </div>
      <div class="col">
      <a href="new_brand.php"><button class="btn waves-effect waves-light" type="submit" name="action">Nova
      </button></a>
      </div>
    </div>
  <?php foreach ($brands as $index => $brand) : ?>
    <ul class="collection registered brands">
      <li class="collection-item"> <?= $brand ?> </li>
    </ul>
  <?php endforeach ?>
</section>

<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
