<?php
define("DB_PATH", "../../../database/brand.txt");

$brands = file(DB_PATH, FILE_IGNORE_NEW_LINES);
?>

<section>
<div>
      <h4>Marcas Informadas</h4>
      <a href="new_brand.php"><button class="btn waves-effect waves-light green " type="submit" name="action">Nova
        </button></a>
    </div>
  <?php foreach ($brands as $index => $brand) : ?>
    <ul class="collection registered brands">
      <li class="collection-item"> <?= $brand ?>

      <div class="right">
              <form action="delete_brand.php" method="POST">
                <input type="hidden" name="_method" value="DELETE">
                <input type="hidden" name="brand_delete" value="<?= $index ?>">
                <button class="waves-effect waves-light btn-small red" type="submit"><i class="material-icons center">delete</i></button>
              </form>
            </div>

      <a href="/pages/brand/edit_brand.php?brand_name=<?= urlencode($brand) ?>" class="right yellow accent-4 waves-effect waves-light btn-small"><i class="material-icons center">edit</i></a>

        <a href="/pages/brand/show_brand.php?brand_name=<?= urlencode($brand) ?>" class="right blue accent-4 waves-effect waves-light btn-small"><i class="material-icons center">search</i></a>


      </li>
      </li>
    </ul>
  <?php endforeach ?>
</section>

<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
