<section>
  <div class="row">
    <form action="<?= route("create.brand")?>" method="POST" class="col s12">
      <div class="row">
        <div class="input-field col s12 m12 l12">
          <input placeholder="Exemplo: FORD" id="brand_name" type="text" class="validate" name="brand_name" required>
          <label for="brand_name">Nome Marca</label>
        </div>
      </div>
      <button class="waves-effect waves-light btn blue" type="submit">Salvar</button>
    </form>
  </div>
</section>
