<?php
define('DB_PATH', '../../../database/cars.txt');

$method = $_SERVER['REQUEST_METHOD'];

if ($method === 'POST' && ($_POST['car']) && !empty($_POST['car'])) {
  $cars = $_POST['car'];
  file_put_contents(DB_PATH, $cars . PHP_EOL, FILE_APPEND);
}



$cars = file(DB_PATH, FILE_IGNORE_NEW_LINES)

?>

<div class="container">
  <section>
    <h4>Carros Informados</h4>
    <?php foreach ($cars as $index => $car) : ?>
      <ul class="collection registered cars">
        <li class="collection-item"> <?= $car ?> </li>
      </ul>
    <?php endforeach ?>
  </section>
</div>
<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
