<?php
define('DB_PATH', '../../../database/cars.txt');


$cars = file(DB_PATH, FILE_IGNORE_NEW_LINES)

?>

<div class="container">
  <section>
    <h4>Carros Informados</h4>
    <?php foreach ($cars as $index => $car) : ?>
      <ul class="collection registered cars">
        <li class="collection-item"> <?= $car ?> </li>
      </ul>
    <?php endforeach ?>
  </section>
</div>
<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
