<section>
    <div class="row">
      <form action="<?= route("create.car")?>" method="POST" class="col s12">
        <div class="row">
          <div class="input-field col s12 m12 l12">
            <input placeholder="Exemplo: GOL" id="car_name" type="text" class="validate" name="car" required>
            <label for="car_name">Nome Carro</label>
          </div>
        </div>
        <button class="waves-effect waves-light btn blue" type="submit" >Salvar</button>
      </form>
    </div>
  </section>
