name: Continuous Integration with Github Actions

on:
  push:


jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
    
      - name: Composer install
        run: ./run composer install

      - name: DB Reset  
        run: ./run db:reset

      - name: PHPUNIT
        run: ./run test
  code_quality:
    name: Code_Quality_Check 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
    
      - name: Composer install
        run: ./run composer install

      - name: DB Reset  
        run: ./run db:reset  

      - name: PHPCS
        run: ./run phpcs

      - name: PHPSTAN
        run: ./run phpstan           
