<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="/assets/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="/assets/js/materialize.min.js"></script>
  <script src="/assets/js/teste.js"></script>
</head>

<body>
  <section>
    <nav>
      <div class="nav-wrapper blue darken-4">
        <a class="brand-logo center">Lista de Marcas e Carros</a>
        <ul id="nav-mobile" class="left ">
          <li><a href="<?= route("brands.list") ?>">Marcas</a></li>
          <li><a href="<?= route("cars") ?>">Carros</a></li>
        </ul>
        <?php if ($this->currentUser()) : ?>
          <ul id="nav-mobile" class="right ">
            <li><span class="white-text"><?=$this->currentUser->getName()?></span></li>
            <li><a href="<?= route("logout") ?>"><button class="waves-effect waves-light btn-flat red darken-1"><span class="white-text">SAIR</span></button></a></li>
          </ul>
        <?php endif; ?>
      </div>
    </nav>
  </section>
  <br>
  <div class="container">
    <nav>
      <div class="nav-wrapper blue darken-4 center"> <?= $title ?> </div>

    </nav>
    <br>
    <?php require "_flashMessage.phtml"; ?>
    <?php require $view ?>
  </div>
</body>

</html>