<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
  <section>
    <nav>
      <div class="nav-wrapper blue darken-4">
        <a  class="brand-logo center">Carros</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="./pages/brand/new.php">Marcas</a></li>
        </ul>
      </div>
    </nav>
  </section>
  <br>
  <div class="container">
    <nav>
      <div class="nav-wrapper blue darken-4 center"> <?= $title ?> </div>
    </nav>
    <br>
    <?php require $view ?>
  </div>
</body>

</html>
